---
- hosts: prod #categoria das maquinas dentro do arquivo de inventario
  gather_facts: no
  serial: 30

  tasks:
  - name: Encontrando as VMs no Ambiente
    vmware_guest_find:
      hostname: "{{ VMWARE_HOST }}"
      username: "{{ VMWARE_USER }}"
      password: "{{ VMWARE_PASSWORD }}"
      validate_certs: no
      name: "{{ inventory_hostname }}"
    delegate_to: localhost
    register: vm_folder
    
  - name: Efetuando o snapshot das VMS
    vmware_guest_snapshot:
      hostname: "{{ VMWARE_HOST }}"
      username: "{{ VMWARE_USER }}"
      password: "{{ VMWARE_PASSWORD }}"
      validate_certs: False
      datacenter: "{{ datacenter_name }}"
      folder: "/{{ vm_folder }}/vm/"
      name: "{{ inventory_hostname }}"
      state: present
      snapshot_name: "WINDOWS_UPDATE_SNAPSHOT"
      description: SNAPSHOT CAPTURADO PELO ANSIBLE ANTES DE APLICAR UPDATES NO AMBIENTE
    delegate_to: localhost
